More trigger options and side panel width
weweb-assets/navigation-menu pull request #4
Opened 2021-08-17 10:22 UTC by kevinbarfleur

2021-08-17 13:42 UTC, AurelieV requested changes

2021-08-17 13:42 UTC, AurelieV commented on src/configuration.js
> +        ...(function () {
pourquoi passer par une fonction?

2021-08-17 13:42 UTC, AurelieV commented on src/wwObject.vue
> +        <wwObject
Si on voulait être 100% propre, il faudrait toujours que ce soit un tag button qui wrappe tout ça :s

2021-08-17 13:42 UTC, AurelieV commented on src/wwObject.vue
> +        icon: wwLib.element('ww-icon'),
ici les éléments existeront toujours pour chaque nav, même si on ne les utilise pas. a voir si c'est ok

2021-08-17 13:42 UTC, AurelieV commented on src/wwObject.vue
> +        icon: wwLib.element('ww-icon'),
(je pense que oui, car comme le type est responsive, ca va ptetre faire pas mal de truc à réfléchir)

2021-08-17 13:42 UTC, AurelieV commented on src/wwObject.vue
> +        --menu-size: '60%';
pourquoi le définir ici?

2021-08-17 14:03 UTC, kevinbarfleur commented on src/configuration.js
> +        ...(function () {
C'est toujours comme ça que j'ai fait pour avoir une/des props conditionnelles. Mais le fait que tu ais relevé le point m'a fait me poser la question. Tu imaginais plus quelque chose comme ça ? :

`menuSize:
            content.menuType === 'right' || content.menuType === 'left'
                ? {
                      menuSize: {
                          type: 'Length',
                          label: {
                              en: 'Menu size',
                              fr: 'Menu size',
                          },
                          options: {
                              unitChoices: [{ value: '%', label: '%', min: 20, max: 100 }],
                          },
                      },
                  }
                : {},`

2021-08-17 14:10 UTC, kevinbarfleur commented on src/wwObject.vue
> +        <wwObject
Un truc du genre ?

```html
<button class="navigation-menu__trigger">
     <button class="navigation-menu__trigger" :style="iconStyle" @click="triggerToggle">
            <wwObject v-if="content.triggerType === 'button'" v-bind="content.button" ww-responsive="menu-button">
                Toggle
            </wwObject>
            <wwObject
                v-else-if="content.triggerType === 'icon'"
                v-bind="content.icon"
                ww-responsive="menu-button"
            ></wwObject>
            <wwObject v-else v-bind="content.image" ww-responsive="menu-button"></wwObject>
        </button>      
</button>
```

2021-08-17 14:15 UTC, kevinbarfleur commented on src/wwObject.vue
> +        --menu-size: '60%';
Car c'est directement ici que j'insère la computed avec la variable :

```html
<div
                class="navigation-menu__panel"
                :class="[content.menuType, { full: content.fullHeight }]"
                :style="navigationPanelStyle"
            >
                <wwLayout
                    class="navigation-menu__panel-items"
                    :class="{ '-pushLast': !!content.pushLast }"
                    path="elements"
                ></wwLayout>
            </div>
```

Ça pose problème que ça ne soit pas à la racine ? Vu que c'est utilisé à un seul endroit

2021-09-03 07:50 UTC, Kramerbaf commented on src/wwObject.vue
> +        icon: wwLib.element('ww-icon'),
Ce qui est embêtant c'est qu'ils vont tout les 2 apparaitre dans le navigator du coup, même si ils ne sont pas utilisés.

2021-09-29 13:23 UTC, merged